[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_key_storage = "2FCmh5tZDnu7V1wFjwj6JSuGs2nVkBViUKh8zkXYiRQF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/my-solana-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
